version: "3.7"

services:

  openldap:
    image: registry$DNS_SUFFIX/usine-logicielle/openldap
    networks:
      - back-network
    volumes:
      - openldap-var-volume:/var/lib/ldap
      - openldap-etc-volume:/etc/ldap/slapd.d
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.directory == true

  phpldapadmin:
    image: registry$DNS_SUFFIX/usine-logicielle/phpldapadmin
    networks:
      - front-network
      - back-network
    volumes:
      - phpldapadmin-volume:/var/www/phpldapadmin
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.directory == true
      labels:
        - "traefik.docker.network=front-network"
        - "traefik.http.routers.directory.entrypoints=https"
        - "traefik.http.routers.directory.tls=true"
        - "traefik.http.routers.directory.tls.certresolver=myhttpchallenge"
        - "traefik.http.routers.directory.rule=Host(`directory$DNS_SUFFIX`)"
        - "traefik.http.services.directory.loadbalancer.server.port=80"

volumes:

  openldap-var-volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=UL-Storage-VM
      device: :/data/openldap-var

  openldap-etc-volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=UL-Storage-VM
      device: :/data/openldap-etc

  phpldapadmin-volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=UL-Storage-VM
      device: :/data/phpldapadmin

networks:

  front-network:
    external: true

  back-network:
    external: true
