version: "3.7"

services:

  gitlab:
    image: registry$DNS_SUFFIX/usine-logicielle/gitlab
    networks:
      - back-network
      - front-network
    volumes:
      - gitlab-volume:/var/opt/gitlab
    deploy:
      placement:
        constraints:
          - node.role != manager
          - node.labels.vcs == true
      labels:
        - "traefik.docker.network=front-network"
        - "traefik.http.routers.vcs.entrypoints=https"
        - "traefik.http.routers.vcs.tls=true"
        - "traefik.http.routers.vcs.tls.certresolver=myhttpchallenge"
        - "traefik.http.routers.vcs.rule=Host(`vcs$DNS_SUFFIX`)"
        - "traefik.http.services.vcs.loadbalancer.server.port=80"

volumes:

  gitlab-volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=UL-Storage-VM
      device: :/data/gitlab

networks:

  front-network:
    external: true

  back-network:
    external: true
